// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping.ProductApi.Model.Context;

#nullable disable

namespace Shopping.ProductApi.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shopping.ProductApi.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Category 2",
                            Description = "description 2",
                            ImageUrl = "https://img.freepik.com/vetores-gratis/laptop-com-icone-de-codigo-isometrico-de-programa-desenvolvimento-de-software-e-aplicacoes-de-programacao-neon-escuro_39422-971.jpg?w=900&t=st=1685310716~exp=1685311316~hmac=3cd629e566448fc8a3763222d3d91716ce22747d805a80c51c4c403bd1f1980e",
                            Name = "Name 2",
                            Price = 79.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Category 3",
                            Description = "description 3",
                            ImageUrl = "https://img.freepik.com/vetores-gratis/ilustracao-do-conceito-de-digitacao-de-codigo_114360-3581.jpg?w=740&t=st=1685310825~exp=1685311425~hmac=973fd53fa3054f2deee21284d6197659915e0cb63215cbf7125daa2689ee1ac7",
                            Name = "Name 3",
                            Price = 79.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Category 4",
                            Description = "description 4",
                            ImageUrl = "https://img.freepik.com/psd-premium/psd-de-maquete-de-sacola-de-compras-em-um-apartamento-moderno_53876-137778.jpg?w=996",
                            Name = "Name 4",
                            Price = 79.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
